name: Build C++ Application

on:
  push:
    branches:
      - main  # O workflow será acionado em push na branch main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Compile C++ code
      run: |
        mkdir -p bin
        g++ -o bin/application Main.cpp 

    - name: Upload the binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: bin/application
